# 应用名称
#spring.application.name=demo

# 应用服务 WEB 访问端口
#server.port=8888
#spring.datasource.url = jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
#spring.datasource.data-username= root
#spring.datasource.data-password= 123456
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver


